server:
  port: ${PORT:8079}
  servlet:
    context-path: /
spring:
  liquibase:
    enabled: true 
    change-log: classpath:changelog/db.changelog-master.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    hikari:
      maximum-pool-size: 3

  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
#        format_sql:true
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none

  jackson:
    serialization:
      indent_output: true

jwt:
  header: Authorization
  secret: proselyte
  expiration: 604800
