server:
  port: ${PORT:8079}
  servlet:
    context-path:
spring:
  liquibase:
    enabled: false
    change-log: classpath:changelog/db.changelog-master.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/realestatenotifier}
    username: ${SPRING_DATASOURCE_USERNAME:mihailzubarev}
    password: ${SPRING_DATASOURCE_PASSWORD:_Akvilani33}

  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
#        format_sql:true
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none

  jackson:
    serialization:
      indent_output: true

jwt:
  header: Authorization
  secret: proselyte
  expiration: 604800
